-- "Riwayat Briefing" history for Ringkasan Harian -- a snapshot of that
-- day's real computed summaryText, saved opportunistically whenever the
-- page loads (so it's only ever real data the user actually generated by
-- visiting that day, never backfilled/fabricated for days they didn't).
create table public.daily_briefings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id),
  briefing_date date not null,
  preview text not null,
  created_at timestamptz not null default now(),
  unique (user_id, briefing_date)
);

create index idx_daily_briefings_user_date on public.daily_briefings using btree (user_id, briefing_date desc);

alter table public.daily_briefings enable row level security;

create policy daily_briefings_owner_select on public.daily_briefings for select using (auth.uid() = user_id);
create policy daily_briefings_owner_insert on public.daily_briefings for insert with check (auth.uid() = user_id);
create policy daily_briefings_owner_update on public.daily_briefings for update using (auth.uid() = user_id);
create policy daily_briefings_owner_delete on public.daily_briefings for delete using (auth.uid() = user_id);
